### ISSUE TITLE
간단한 API 서버 코드 작성

### ISSUE THREAD

**Issue by modolee** [Day34/day34-boilerplate-nodejs#1]
# 추가/개선 필요 요소
Express를 이용해서 간단한 REST API를 생성

# 추가/개선 필요 이유
기본 서버 구성 및 샘플 API 코드를 작성해야 한다.

# 상세 요구 사항
GET, POST 메소드로 API 하나씩 작성

# 스크린샷
없음

**Comment by easternbear** [comment]
작업 시작..

**Comment by easternbear** [comment]
코드 리팩토링은 기능 요구사항 정리가 어느정도 끝난 이후에 진행 하겠음

**Comment by modolee** [comment]
PR에는 label 없이 진행하고 ISSUE에만 label 달아주세요 :)
