### ISSUE TITLE
환경 변수가 없어서 에러 발생

### ISSUE THREAD

**Issue by modolee** [Day34/day34-boilerplate-nodejs#15]
# 발생 일시
2019.11.26

# 발생 위치
컨테이너를 띄우고 서버를 실행 했을 때

# 증상
`App listening on undefined:undefined`
메세지가 발생하면서 동작하지 않음

# 재현 방법
`docker-compose up --build`

# 스크린샷

**Comment by modolee** [comment]
`require('custom-env').env()` 이 부분을 local에서만 사용해야 되는데 dev, prod 모두 사용하고 있어서 발생하는게 아닐까 생각
local에서도 .env 파일이 아니라 docker-compose에 environment 로 넣어야 되나 고민 중
env_file 과 다른 점은 무엇인지 찾아 봐야 됨

**Comment by easternbear** [comment]
require('custom-env').env() 를 없애도 될거같은데?...

**Comment by modolee** [comment]
해당 패키지 제거하고 작업 중입니다. :)

**Comment by easternbear** [comment]
넵!
