### ISSUE TITLE
CI 툴 선택 및 설정 파일 추가

### ISSUE THREAD

**Issue by modolee** [Day34/day34-boilerplate-nodejs#4]
# 추가/개선 필요 요소
CI 툴 선택 및 설정 파일 추가

# 추가/개선 필요 이유
우리가 사용하기 적합한 CI 툴을 선택하고, 해당 CI 툴 사용을 위한 설정 파일을 작성한다.

# 상세 요구 사항
#3 에서 선택 된 저장소를 사용하기 좋은 CI 툴을 선택한다.

다음 툴을 비교한다.
- Travis CI
- Circle CI
 - ETC.

# 스크린샷
없음

**Comment by modolee** [comment]
https://medium.com/day34/ci-cd-tool-comparison-f710a4777852?sk=5b9fff46e0a19f9a4d38b0a063f4a752

**Comment by modolee** [comment]
결론은 AWS ECS 배포 가능하고, 가격 저렴한 Circle CI로 가즈아

**Comment by modolee** [comment]
설정 파일 추가가 안됐네요. ㅠㅠ
CircleCI 설정 파일 추가해서 배포까지는 아니고 통합 테스트 하는 것까지 작성하고 이슈 닫겠습니다.

**Comment by easternbear** [comment]
tj

> 설정 파일 추가가 안됐네요. ㅠㅠ
> CircleCI 설정 파일 추가해서 배포까지는 아니고 통합 테스트 하는 것까지 작성하고 이슈 닫겠습니다.

설정파일 추가 되면 PR좀 날려주세요

**Comment by modolee** [comment]
넵~

**Comment by modolee** [comment]
test 실행 후 CI 프로세스가 종료되지 않음
그 부분을 수정해야 됨

**Comment by easternbear** [comment]
package.json 에 npm test 스크립트에 설정되어있는 --coverage 때문인거같은데 ... 옵션중 CI=true
이걸로 바꾸면 되지 않아?

**Comment by easternbear** [comment]
트라비스도 test가 종료되지 않았었는데 -e CI=true 넣어주니까 되던데
```
docker run -e **CI=true** 컨테이너태그명 npm test 
```

**Comment by modolee** [comment]
CI=true 는 안먹힘

아래와 같은 메세지가 나와서 해볼 예정

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by easternbear** [comment]
resolve 했은데 종료가 안되네.. 일단 이슈 닫겠음

**Comment by modolee** [comment]
master 브랜치에 합쳐져야 자동으로 closed 됨
